plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.kafka:spring-kafka'

    // PostgreSQL
    runtimeOnly 'org.postgresql:postgresql'

    // Flyway (Spring Boot 3.x 에서 PostgreSQL 지원 모듈 분리)
    implementation 'org.flywaydb:flyway-core'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql'

    // FCM (Firebase Cloud Messaging)
    implementation 'com.google.firebase:firebase-admin:9.2.0'
}